version: '3.1'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rxqfifwqtzmrjmzy
      POSTGRES_DB: book_store_db
    volumes:
      - pgdata:/var/lib/postgresql/bookstore/data
volumes:
  pgdata: